export const PROMPT = 'You are Luna, a warm, thoughtful voice companion. Speak natural English. Keep each reply to one or two short sentences, usually under 45 words. Answer directly, leave room for back-and-forth, and follow the person’s lead. If interrupted or corrected, adapt immediately. Do not use markdown, stage directions, or pretend to have performed actions. Wait for the person to speak first.';
export const PROVIDERS = [
  { id: 'openai', name: 'OpenAI Realtime', kind: 'Native speech', mark: '01', color: 'sage', description: 'One model listens, reasons, and speaks. A strong baseline for fluid interruptions.', path: ['Audio', 'Realtime', 'Audio'], model: 'gpt-realtime-2.1', needs: ['OPENAI_API_KEY'], source: 'https://github.com/openai/openai-realtime-agents' },
  { id: 'gemini', name: 'Gemini Live', kind: 'Native speech', mark: '02', color: 'blue', description: 'A second native-audio approach, with its own voice, pacing, and turn detection.', path: ['Audio', 'Gemini Live', 'Audio'], model: 'gemini-3.8-live', needs: ['GEMINI_API_KEY'], source: 'https://github.com/google-gemini/live-api-web-console' },
  { id: 'eleven', name: 'ElevenLabs Agents', kind: 'Managed conversation', mark: '03', color: 'sand', description: 'Expressive speech with managed transcription and conversation timing.', path: ['Scribe', 'Hosted AI', 'ElevenLabs'], model: 'gpt-6-luna + eleven_v4_turbo', needs: ['ELEVENLABS_API_KEY'], source: 'https://github.com/elevenlabs/packages' },
  { id: 'deepgram', name: 'Deepgram Agent', kind: 'Managed pipeline', mark: '04', color: 'rose', description: 'Streaming recognition, hosted reasoning, and speech behind one connection.', path: ['Nova 3', 'GPT-4o mini', 'Aura 2'], model: 'nova-3 / gpt-4o-mini / aura-2-thalia-en', needs: ['DEEPGRAM_API_KEY'], source: 'https://github.com/deepgram-starters/node-voice-agent' },
  { id: 'groq', name: 'Groq × ElevenLabs', kind: 'Independent pipeline', mark: '05', color: 'clay', description: 'Hosted Whisper and a fast text model, with speech streamed phrase by phrase.', path: ['Groq Whisper', 'Groq AI', 'ElevenLabs'], model: 'whisper-large-v3-turbo / llama-3.1-8b-instant', needs: ['GROQ_API_KEY', 'ELEVENLABS_API_KEY'], source: 'https://github.com/automataIA/realtime-voice-agent' },
  { id: 'local', name: 'Luna, in house', kind: 'The local challenger', mark: '06', color: 'lavender', description: 'Your browser does the listening. Only the transcript goes to AI; ElevenLabs gives it a voice.', path: ['Local Moonshine', 'Your choice of AI', 'ElevenLabs'], model: 'Moonshine tiny · browser WASM', needs: ['ELEVENLABS_API_KEY'], source: 'https://github.com/Superactive-AI/inbrowser-ai' },
];
export const SCENARIOS = [
  { name: 'A natural start', text: 'I have a math test tomorrow and I keep putting off studying. Can you help me get started?' },
  { name: 'A tiny response', text: 'Ask me whether I would rather study algebra or geometry. Then wait for my answer.', follow: 'Answer with just “algebra,” then just “yes” to its next question.' },
  { name: 'Change your mind', text: 'Explain how derivatives work.', follow: 'Interrupt: “Wait, actually, start with slope. Keep it really simple.”' },
  { name: 'Room to think', text: 'I think the answer is…', follow: 'Pause for a second, then finish: “actually, I’m not sure. Maybe twelve?”' },
];
