import assert from 'node:assert/strict';
import { EventEmitter, once } from 'node:events';
import { createServer } from 'node:http';
import WebSocket from 'ws';
import { attachLiveVoice } from '../../server/live-voice.mjs';
import { createHintPolicy, createHintPolicyStore } from '../../server/hint-policy.mjs';
export function virtualClock() { let at=1_000_000,next=0;const tasks=new Map();return {now:()=>at,setTimeout(fn,ms){const id=++next;tasks.set(id,{fn,at:at+ms});return id;},clearTimeout:id=>tasks.delete(id),advance(ms){const end=at+ms;let count=0;while(true){const hit=[...tasks].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!hit)break;assert.ok(++count<1000,'no timer loop');tasks.delete(hit[0]);at=hit[1].at;hit[1].fn();}at=end;}};}
export const question={id:'q-diffusion',topicId:'transport',topicTitle:'Transport',difficulty:'easy',question:'Which way do particles diffuse?',answer:'PRIVATE ANSWER',sourceIds:['notes']};
export const study={testId:'18e2ced5-fab7-4b23-ae07-abc99c94a421',title:'Biology',date:'',indexStatus:'ready',materials:[{id:'notes',name:'Notes',text:'Particles diffuse from higher to lower concentration.'}]};
export async function sessionFixture(t,{start=study,greeting={reply:question.question,questionId:question.id},autoEnd=true,intent,integrations={}}={}){
 const clock=virtualClock(),messages=[],calls=[],speech=[],sockets=[],events=new EventEmitter();let consumed=0;
 const notify=()=>events.emit('change');const waitFor=(pred,label='event')=>pred()?Promise.resolve():new Promise((resolve,reject)=>{const timer=setTimeout(()=>{events.off('change',check);reject(Error(`Timed out: ${label}`));},1500);function check(){if(pred()){clearTimeout(timer);events.off('change',check);resolve();}}events.on('change',check);});
 class STT extends EventEmitter{constructor(){super();this.readyState=1;this.bufferedAmount=0;this.sent=[];sockets.push(this);queueMicrotask(()=>this.receive({message_type:'session_started'}));}receive(value){this.emit('message',Buffer.from(JSON.stringify(value)));}terminate(){this.readyState=3;this.emit('close');}send(value,cb){this.sent.push(JSON.parse(value));cb?.();}}
 const server=createServer();const attached=attachLiveVoice(server,{env:{LIVE_APIS:'true',ELEVENLABS_API_KEY:'mock'},cliOrganizer:{available:true},sessionTiming:clock,createHintPolicyImpl:()=>createHintPolicy({store:createHintPolicyStore({now:clock.now})}),WebSocketImpl:STT,
 questionBank:{topics:()=>[],context:()=>({topics:[{title:'Transport',questions:[question]}]}),resolve:(_,id)=>id===question.id?question:null,consumeById:(_,id,reply)=>{if(id===question.id&&reply===question.question&&!consumed++){return[question];}return[];},consume:()=>[],discard(){}},
 masteryStore:{load:async()=>({overall:0,topics:[]}),pendingNotices:async()=>[],setTopics:async()=>({overall:0,topics:[]})},
 intentRouter:{classify:text=>intent?.(text)||{requestsHelp:text==='help',answerAttempt:false,examDeadline:false}},canvasRouter:{classify:async()=>({needsCanvas:false})},
 createLunaFastImpl:()=>({ready:async()=>{},close:async()=>{},respond(input,options){if(input.readinessContext.trigger==='session-start'){calls.push({input,options,greeting:true});options.onText?.(greeting.reply);return Promise.resolve(greeting);}return new Promise((resolve,reject)=>{calls.push({input,options,resolve,reject});notify();});}}),
 createSpeechStreamImpl:options=>{const stream={options,text:'',ended:false,write(text){this.text+=text;},finish(){this.finished=true;if(autoEnd)queueMicrotask(()=>{this.ended=true;options.onEnd();notify();});},cancel(){this.canceled=true;}};speech.push(stream);return stream;},...integrations});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;const client=new WebSocket(origin.replace('http:','ws:')+'/api/live-voice',{origin});client.on('message',data=>{messages.push(JSON.parse(data));notify();});await once(client,'open');client.send(JSON.stringify({type:'start',...start}));t.after(async()=>{client.terminate();await attached.close();await new Promise(resolve=>server.close(resolve));});
 await waitFor(()=>messages.some(x=>x.final),'greeting');
 const flush=async()=>{await new Promise(resolve=>setImmediate(resolve));const pong=once(client,'pong');client.ping();await pong;await new Promise(resolve=>setImmediate(resolve));};
 return {clock,messages,calls,speech,sockets,waitFor,flush,client,get consumed(){return consumed;},async packet(value){client.send(JSON.stringify(value));await flush();},async advance(ms){clock.advance(ms);await flush();},async commit(text){sockets.at(-1).receive({message_type:'committed_transcript',text});await flush();},async partial(text){sockets.at(-1).receive({message_type:'partial_transcript',text});await flush();},async complete(call,reply='Try identifying the direction first.'){call.options.onText?.(reply);call.resolve({reply});await flush();},async end(){const s=speech.at(-1);s.ended=true;s.options.onEnd();await flush();}};
}
